services:
  - type: web
    name: signai-backend
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn run:app --bind=0.0.0.0:$PORT --workers=2 --timeout=120
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 8000
      - key: FLASK_ENV
        value: production
      - key: SESSION_SECRET
        sync: false 